before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly libpcap-dev
script:
  - git clone http://github.com/colemickens/rust-pcap;
  - cd rust-pcap
  - make
  - cd ..
  - git clone http://github.com/colemickens/rust-packet
  - cd rust-packet
  - make
  - make test
  - cd ..
  - rustc main.rs -L ./rust-pcap -L ./rust-packet
